Week1 필수과제
GO-SOPT-ANDROID/SeonHwan-Kim pull request #1
Opened 2023-04-05 10:34 UTC by SeonHwan-Kim

## 필수과제 수행
- 로그인 페이지
  - [ ] id, password 일치 시 로그인
  - [ ] 성공했습니다 toast 메세지
  - [ ] 비밀번호 보이지 않게 하기
- 회원가입 페이지
  - [ ] 회원가입 성공 조건 만족시키기
  - [ ] 스낵바 띄우기
- 메인 페이지
  - [ ] 이름과 특기 불러오기
  
## 부족한 부분
- [ ] userdata 분리?
- [ ] 파일 분리시키기?

2023-04-07 14:39 UTC, skylartosf approved these changes
멋.찌.다. 선환아

2023-04-07 14:39 UTC, skylartosf commented on app/src/main/java/org/android/go/sopt/login/LoginActivity.kt
> +            specialty = result.data?.getStringExtra("specialty") ?: ""
이 4개의 변수를 갖는 data class를 만들어도 좋을 듯!

2023-04-07 14:39 UTC, skylartosf commented on app/src/main/java/org/android/go/sopt/main/MainActivity.kt
> +        this.getMyData()
이 this는 머지..?!
없어도 되지 않나!?

2023-04-07 14:46 UTC, SeonHwan-Kim commented on app/src/main/java/org/android/go/sopt/main/MainActivity.kt
> +        this.getMyData()
오.. 없애고 다시 올릴게

2023-04-07 14:47 UTC, SeonHwan-Kim commented on app/src/main/java/org/android/go/sopt/login/LoginActivity.kt
> +            specialty = result.data?.getStringExtra("specialty") ?: ""
한 번 시도해볼게!!

2023-04-08 00:40 UTC, daehwan2da requested changes

2023-04-08 00:40 UTC, daehwan2da commented on app/src/main/java/org/android/go/sopt/login/LoginActivity.kt
> +            if (id == binding.etMainId.text.toString() && password == binding.etMainPassword.text.toString()) {
로그인 버튼을 눌렀을때 id, password 의 유효성을 검사하는 로직인데요,
전제는 etMainId 와 etMainPassword 가 채워져있다는 전제로 해당 로직이 돌아갈것같은데,

만약 etMainId 나 etMainPasswor 가 채워지지 않은 상태로 로그인 버튼을 누르면 어떻게 될까요?
이 부분에 대한 대응이 필요할 것 같습니다.

ex) 값이 입력되지 않았다고 Toast 를 띄어준다던지

추가로.. 학습 목적으로 질문하나 드리면, (저도 잘몰라서..)
binding.etMainId.text 가 java 코드로 되어있어서 아마 null 에 취약할 텐데요,
toString() 을 호출할때 NPE (NullPointerException) 이 발생할 수 있는지 코드안을 파보면 좋을것같네요~
어려우면 이따 같이해봅시다
(개인적 추측은 아마 null 이 아니라, empty ("") 형태로 값을 가지고있을것같은..)

2023-04-08 00:40 UTC, daehwan2da commented on app/src/main/java/org/android/go/sopt/login/LoginActivity.kt
> +                intent.putExtra("specialty", specialty)
여기서 "name", "specialty" 와 같은 부분은 매직리터럴이라고 합니다~
만약 MainActivity 에서 intent 로 부터 담긴 value 를 꺼내올때 key 에 오타가 있으면 컴파일 시점에는 잡히지 않는데, 
런타임 시점에서는 버그로 발생되어지겠죵?

2023-04-08 00:40 UTC, daehwan2da commented on app/src/main/java/org/android/go/sopt/login/LoginActivity.kt
> +                showShortToast(getString(R.string.login_success_login_msg))
Login -> Main 으로 액티비티 전환이 일어나면 Login 액티비티는 어떻게 하면 좋을까요?

2023-04-08 00:40 UTC, daehwan2da commented on app/src/main/java/org/android/go/sopt/main/MainActivity.kt
> +        this.getMyData()
없어도 되긴한데, 개인 코딩 스타일이라고 생각하네요~ 오히려 명시적이기도 합니다~

2023-04-08 00:40 UTC, daehwan2da commented on app/src/main/java/org/android/go/sopt/signup/SignUpActivity.kt
> +            if(id.length !in 6..10){
이런 if, else 처리는 개인적으로 코틀린 스럽지 않다고 생각되어지고요..
이런거 해결하는 방법들을 코틀린스럽게 에서 알려줄게요~

2023-04-08 05:12 UTC, SeonHwan-Kim commented on app/src/main/java/org/android/go/sopt/login/LoginActivity.kt
> +            if (id == binding.etMainId.text.toString() && password == binding.etMainPassword.text.toString()) {
그 etMainId나 etMainPassword가 채워지지 않은 상태에서는 앱이 꺼지더라고요!
그래서 예외처리 해서 다시 코드 올리겠습니다!

2023-04-10 05:21 UTC, SeonHwan-Kim commented on app/src/main/java/org/android/go/sopt/signup/SignUpActivity.kt
> +            if(id.length !in 6..10){
넵!!

2023-04-10 08:33 UTC, Bewheneverwhatiwant commented on app/src/main/java/org/android/go/sopt/login/LoginActivity.kt
> +            if (id == binding.etMainId.text.toString() && password == binding.etMainPassword.text.toString()) {
오 대박 이 부분 멋있당

2023-04-13 10:27 UTC, SeonHwan-Kim commented on app/src/main/java/org/android/go/sopt/login/LoginActivity.kt
> +                showShortToast(getString(R.string.login_success_login_msg))
Login 액티비티를 finish() 시켰습니다!

2023-04-16 11:29 UTC, merged

2023-05-14 14:55 UTC, skylartosf approved these changes
성환이...최고.....💝