Week4
GO-SOPT-ANDROID/SeonHwan-Kim pull request #8
Opened 2023-05-12 14:56 UTC by SeonHwan-Kim

# 이슈
- #7 

# 작업 내용
## 필수 과제
- 진짜 회원가입/로그인
  - 모든 입력값을 받으면 회원가입 버튼 클릭 할 수 있도록 수정
  - 서버 통신하여 회원가입하기
  - 로그인 api 연동
  - 실패시..?

- Home 화면 꾸미기

## 심화 과제
- Search Fragment 꾸미기
  - 주어진 키워드 입력 후 검색 버튼 클릭 시 API 통신
  - 성공적으로 응답이 된 경우 검색 입력창 하단이 리스트로 바뀌어져 검색 결과 리스트 보여주기
  - 검색 결과가 비어있다면 Empty UI 로 구성

2023-05-13 01:36 UTC, daehwan2da requested changes

2023-05-13 01:36 UTC, daehwan2da commented on app/src/main/java/org/android/go/sopt/data/remote/model/SignInDto.kt
> +data class ResponseSignInDto(
SignIn, SignUp Dto 보면 공통으로 json object 로 감싸지는 영역들이 있는데요,
(status, message, data)
이런 부분들은 추상화 시켜서 중복을 제거해보는건 어떨까요?

- 적용해볼것
  - Generic 활용
- 관련해 공부해보면 좋은 내용
  - 객체지향
  - Generic in kotlin

2023-05-13 01:36 UTC, daehwan2da commented on app/src/main/java/org/android/go/sopt/data/remote/service/HomeUserService.kt
> +    @GET("users?page=2")
page 가 static 하게 2로 박혀있는 이유가 있을까요?
실제 앱을 구현하게 될때는 동적으로 받게될텐데, 적용해봐도 도움될것같네요

2023-05-13 01:36 UTC, daehwan2da commented on app/src/main/java/org/android/go/sopt/data/remote/service/KakaoSearchService.kt
> +        @Header("Authorization") apiKey: String = BuildConfig.KAKAO_AUTH_HEADER,
매 요청마다 Authorization header 를 추가해주어야할 수도있는데, 
어떻게 하면 매번 추가하는 header 를 생략할 수 있을까요?
(추가로, 매번 이렇게 추가하는게 나쁜건 아니지만, 어떤 문제점이 발생할 수 있을까요? (귀찮음 빼고) )

2023-05-13 01:36 UTC, daehwan2da commented on app/src/main/java/org/android/go/sopt/data/remote/service/SignUpService.kt
> +// suspend 함수?
coroutine 을 사용하면 suspend fun 을 활용하게 되겠네요~ 앱잼때 거의 쓰게되어서,, 공부 꼭 해보면 좋겠네요
(세미나에서 다루겠지만)

2023-05-13 01:36 UTC, daehwan2da commented on app/src/main/java/org/android/go/sopt/presentation/login/LoginActivity.kt
> +    private val signInService = ServicePool.signInService
object class 에서 끌고오는 signInService 는 필드로 받을 필요는 없어보입니다~
바로 로직에서 사용하면 될것같아요

2023-05-13 01:36 UTC, daehwan2da commented on app/src/main/java/org/android/go/sopt/presentation/login/LoginActivity.kt
> +                signInService.signIn(
```suggestion
                ServicePool.signInService.signIn(RequestIsnInDto(et,,, ))
```

2023-05-13 01:36 UTC, daehwan2da commented on app/src/main/java/org/android/go/sopt/presentation/login/LoginActivity.kt
> +                    override fun onFailure(call: Call<ResponseSignInDto>, t: Throwable) {
onFailure 는 언제 발생하게 될까요

2023-05-13 01:36 UTC, daehwan2da commented on app/src/main/java/org/android/go/sopt/presentation/main/gallery/GalleryFragment.kt
> +    private val homeUserService = ServicePool.getHomeUserService
필드에 이렇게 할당해주게 되면 fragment 가 정상적으로 destroy 되지 않지 않을까 싶네요 (추측이지만..)

- 왠만하면 필드를 사용하는것은 좋아보이지 않습니다
  - 메모리 leak 발생 가능
- 꼭 사용해야한다면, binding 처럼 var 를 활용해 nullable 하게 구성한 뒤 destory 에서 할당해제하는 작업을 해주면 안전할 것 같네요

2023-05-14 07:15 UTC, SeonHwan-Kim commented on app/src/main/java/org/android/go/sopt/data/remote/model/SignInDto.kt
> +data class ResponseSignInDto(
한번 공부해보고 수정해보겠습니다!

2023-05-14 07:16 UTC, SeonHwan-Kim commented on app/src/main/java/org/android/go/sopt/data/remote/service/HomeUserService.kt
> +    @GET("users?page=2")
아직 화면에서 page를 받아오는 부분을 구현하지 않아서 우선 page를 static하게 2로 넣어뒀습니다. 후에 page를 받아오는 view를 만들게 되면 동적으로 바꿀 수 있도록 수정하겠습니다!

2023-05-14 07:17 UTC, SeonHwan-Kim commented on app/src/main/java/org/android/go/sopt/data/remote/service/SignUpService.kt
> +// suspend 함수?
넵!!

2023-05-14 07:17 UTC, SeonHwan-Kim commented on app/src/main/java/org/android/go/sopt/presentation/login/LoginActivity.kt
> +    private val signInService = ServicePool.signInService
넵!!!

2023-05-14 14:55 UTC, skylartosf commented
성환이 최고...💝

2023-05-14 14:56 UTC, skylartosf commented on app/src/main/java/org/android/go/sopt/data/remote/model/SignInDto.kt
> +data class ResponseSignInDto(
짱이다..

2023-05-15 06:42 UTC, giovannijunseokim commented
> 성환이 최고...💝

이름 모르는건 아니지 누나..?

2023-05-15 13:31 UTC, daehwan2da commented
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ ..

2023-05-17 03:33 UTC, SeonHwan-Kim commented on app/src/main/java/org/android/go/sopt/data/remote/service/KakaoSearchService.kt
> +        @Header("Authorization") apiKey: String = BuildConfig.KAKAO_AUTH_HEADER,
interceptor를 활용해서 요청을 보내는 방법으로 해결할 수 있을 것 같습니다!
매번 추가하면 중복이 심하고 관리하기 번거롭다는 문제가 발생할 수 있는 것 같네요! 혹시 이 외에 다른 문제점도 있을까요?

2023-05-17 03:38 UTC, SeonHwan-Kim commented on app/src/main/java/org/android/go/sopt/presentation/login/LoginActivity.kt
> +                    override fun onFailure(call: Call<ResponseSignInDto>, t: Throwable) {
네트워크에 연결되지 않는 경우 onFailure가 발생하고 그 외의 에러(4xx, 5xx 등)은 onResponse에서 받아와 예외처리를 하는 것 같습니다!

2023-05-20 03:34 UTC, merged